name: Build and Push Docker Image

on:
  workflow_dispatch:  # Enables manual trigger from GitHub UI 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read version from file
        id: get_version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t goavega-software/docker-nginx-fpm:${{ env.VERSION }} .

      - name: Push Docker image
        run: |
          docker push goavega-software/docker-nginx-fpm:${{ env.VERSION }}
